version: "3.7"
services:

  postgres:
    build: ./docker/postgres
    environment:
      POSTGRES_USER: newsfeed
      POSTGRES_PASSWORD: newsfeed
      POSTGRES_DB: newsfeed

  php-fpm:
    build: ./docker/php
    volumes:
      - .:/var/www/newsfeed
    working_dir: /var/www/newsfeed
    depends_on:
      - composer

  nginx:
    image: nginx:1.17.9-alpine
    volumes:
      - .:/var/www/newsfeed
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - postgres
      - php-fpm
      - node

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        UIDD: ${UID:-1000}
    volumes:
      - ./frontend:/var/www/newsfeed/frontend
    working_dir: /var/www/newsfeed/frontend
    command: /bin/sh -c "yarn install && yarn build && chown -R 1000:1000 /var/www/newsfeed/frontend/dist"
    environment:
      VUE_APP_ENDPOINT: http://localhost:8282/api/v1/
    depends_on:
      - php-fpm

  composer:
    build: ./docker/php
    command: composer install
    volumes:
      - .:/var/www/newsfeed
    working_dir: /var/www/newsfeed
    depends_on:
      - postgres

  phpunit:
    build: ./docker/php
    command: vendor/bin/phpunit --coverage-html=storage/coverage
    working_dir: /var/www/newsfeed
    env_file:
      - ./docker/php/env/testing.env
    volumes:
      - .:/var/www/newsfeed
    links:
      - composer
      - postgres
