version: "3.7"
services:

  postgres:
    image: postgres:12.2-alpine
    volumes:
      - ./docker/postgres/init_testing_db.sql:/docker-entrypoint-initdb.d/init_testing_db.sql
    environment:
      POSTGRES_USER: newsfeed
      POSTGRES_PASSWORD: newsfeed
      POSTGRES_DB: newsfeed

  php-fpm:
    build: ./docker/php
    volumes:
      - .:/var/www/newsfeed
    working_dir: /var/www/newsfeed

  nginx:
    image: nginx:1.17.9-alpine
    volumes:
      - .:/var/www/newsfeed
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - postgres

  composer:
    build: ./docker/php
    command: composer install
    volumes:
      - .:/var/www/newsfeed
    working_dir: /var/www/newsfeed
    depends_on:
      - postgres

  phpunit:
    build: ./docker/php
    command: vendor/bin/phpunit --coverage-html=storage/coverage
    working_dir: /var/www/newsfeed
    env_file:
      - ./docker/php/env/testing.env
    volumes:
      - .:/var/www/newsfeed
    links:
      - composer
      - postgres
